@startuml
class Render {
	- SKCanvas _canvas
	- Scene _scene
	- readonly SceneManager _sceneManager
	+ Render(SceneManager )
	+ void SetCanvas(SKCanvas )
	+ void LoadScene(string , long )
	+ void SetTargetCanvas(SKCanvas )
	+ void GetNextFrame(long timeoff, bool force)
	+ (Dictionary<string, byte[]>, Dictionary<string, byte[]>)
	- void Rendering(long timeoff)
}
@enduml