@startuml
class ResourceManager {
	- readonly HttpClient _httpClient;
	- readonly Dictionary<string, SKBitmap> _imageList
	- readonly Dictionary<string, byte[]> _audioList
	- readonly Dictionary<string, string> _scriptList
	+ string basePath
	+ ResourceManager(HttpClient httpClient)
	+ async Task PullImageAsync(string name, string path)
	+ async Task PullAudioAsync(string name, string path)
	+ async Task PullScriptAsync(string name, string path)
	+ SKBitmap GetImage(string name)
	+ byte[] GetAudio(string name)
	+ string GetScript(string name)
	+ void Clear()
	--Debug--
	+ void PushImageAsync(string name, SKBitmap image)
	+ void PushAudioAsync(string name, byte[] audio)
	+ void PushScriptAsync(string name, string script)
}
@enduml