@startuml
class Animation {
	+ (float X, float Y) BeginPosition 
	+ (float X, float Y) EndPosition
	+ (long) DelayTime
	+ (long) BeginTime
	+ (long) EndTime
	+ Func<float, (float, float)> AniFunction
	+ bool HasAnimation(long timeoff)
	+ (int X, int Y)
}

class AnimationList {
	+ Dictionary<string, Func<float, (float, float)>> Functions
}
@enduml