@startuml
class Scene {
	+ SKSizeI Resolution
	+ bool RenderFlag
	+ Dictionary<string, byte[]>
	+ Dictionary<string, byte[]>
	+ SortedDictionary<int, Layer> Layers
	- readonly Dictionary<string, int>
	- readonly Dictionary<int, string>
	- int _layerCount
	+ void PushLayer(string name, Layer layer)
	+ void Clear()
	+ void SetBeginTime(long beginTime)
	- (SKBitmap In, SKBitmap Out) _fadeMask;
	- (float In, float Out) _fadeTime;
	+ void SetFadeIn(SKBitmap mask, float time)
	+ void SetFadeOut(SKBitmap mask, float time)
}
@enduml