@startuml
struct NodeStructure {
	+ bool IsLeaf
	+ List<UrlStructure>? ResouresPackURL
	+ List<UrlStructure>? NodeURL
	+ List<UrlStructure>? SceneURL
}

struct SceneStructure {
	+ List<UrlStructure>? ResouresPackURL
	+ List<LayerStructure>? Layer
}

struct LayerStructure {
	+ string? Name
	+ bool IsImageLayer
	+ bool IsShapeLayer
	+ bool IsTextLayer
	+ PositonStructure Position
	+ WinSizeStructure WinSize
	+ int Time
	+ string? Animation
	+ PositonStructure BeginPosition
	+ PositonStructure EndPosition
	+ string? Image
	+ ColorStructure ShapeColor
	+ List<TextStructure>? Tex
}

struct TextStructure {
	string? Text
	PositonStructure Offset
	PaintStructure Paint
}

struct PositonStructure {
	int X
	int Y
}
struct WinSizeStructure {
	int Width
	int Height
}
struct PaintStructure {
	ColorStructure Color
	int TextSize
	bool Blod
	bool Antialias
}

struct ColorStructure {
	byte R
	byte G
	byte B
	byte A
}

struct ResouresStructure {
	List<UrlStructure>? ImageURL
	List<UrlStructure>? AudioURL
	List<UrlStructure>? TextURL
};

struct UrlStructure {
	string Name
	string URL
}

struct TestStructure {
	List<UrlStructure>? Test
}
@enduml